# This GitHub Action deploys a static site from the 'public' folder to Azure Web App

name: Deploy static site to Azure Web App - SantosWebApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip static site contents
        run: zip -r release.zip public/*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: static-site
          path: release.zip

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: static-site

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_13B2021E70A4442B8898852DF3C4CC64 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_570C8845874A40B1A4CAFA159EEC7940 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_292F5E8CBAF14138AE04E48139098E6E }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'SantosWebApp'
          slot-name: 'Production'
          package: .

          
