# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy Static Website to Azure Web App - SantosWebApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4  # Checkout your code from GitHub

      - name: Zip static files for deployment
        run: |
          # Zip the files to prepare them for deployment
          zip -r release.zip index.html style.css script.js

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: static-app
          path: release.zip

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: static-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.__clientidsecretname__ }}
          tenant-id: ${{ secrets.__tenantidsecretname__ }}
          subscription-id: ${{ secrets.__subscriptionidsecretname__ }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'SantosWebApp'
          slot-name: 'Production'
          package: .  # Deploy the current directory (after unzipping)
